[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "llvm-internal"
authors = [{name = "Henry Tse", email = "anzihenry@gmail.com"}]
dynamic = ["version", "description"]
